// =============================================================================
// TEMPORARY FIXTURES - LB PRESSING (XAF / FCFA)
// Standardized mock data matching exact Supabase contracts
// =============================================================================

import type { Invoice, Client, Article, User, Organization } from '@/types';

export const LB_PRESSING_ORGANIZATION: Organization = {
  id: 'lb-pressing-org-001',
  name: 'LB Pressing',
  slug: 'lb-pressing',
  ticketPrefix: 'LB',
  country: 'CG',
  phone: '+242 06 800 0000',
  email: 'contact@lbpressing.cg',
  logoUrl: '/images/lb-pressing-logo.png',
  currency: 'XAF',
  settings: {
    currency: 'XAF',
    timezone: 'Africa/Brazzaville',
    taxRate: 0,
    whatsappNumber: '242068000000',
    address: 'Avenue de l\'Indépendance, Brazzaville',
    businessHours: 'Lun - Sam: 07h30 - 19h00'
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const LB_PRESSING_SERVICES: Article[] = [
  {
    id: 'art-001',
    name: 'Chemise Homme / Femme',
    defaultPrice: 1500,
    category: 'vetement',
    isActive: true,
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    description: 'Lavage, repassage soigné sur cintre ou plié',
    estimatedDays: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'art-002',
    name: 'Costume 2 Pièces',
    defaultPrice: 5000,
    category: 'ceremonie',
    isActive: true,
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    description: 'Nettoyage à sec professionnel veste et pantalon',
    estimatedDays: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'art-003',
    name: 'Robe de Soirée / Cérémonie',
    defaultPrice: 7000,
    category: 'ceremonie',
    isActive: true,
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    description: 'Traitement délicat des broderies et dentelles',
    estimatedDays: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'art-004',
    name: 'Tenue Traditionnelle (Pagne / Boubou)',
    defaultPrice: 4000,
    category: 'traditionnel',
    isActive: true,
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    description: 'Soin des couleurs et repassage haute précision',
    estimatedDays: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'art-005',
    name: 'Drap / Couette Lourd',
    defaultPrice: 6000,
    category: 'maison',
    isActive: true,
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    description: 'Lavage antibactérien et séchage grand format',
    estimatedDays: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'art-006',
    name: 'Chaussures / Baskets Premium',
    defaultPrice: 3500,
    category: 'chaussure',
    isActive: true,
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    description: 'Rénovation complète semelle, tige et lacets',
    estimatedDays: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_ORDERS: Invoice[] = [
  {
    id: 'ord-001',
    number: 'LB-0042',
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    clientName: 'Matingou Christian',
    clientPhone: '+242066112233',
    clientEmail: 'christian.matingou@gmail.com',
    clientAddress: 'Poto-Poto, Rue Congo',
    items: [
      {
        articleId: 'art-001',
        name: 'Chemise Homme / Femme',
        category: 'vetement',
        quantity: 3,
        unitPrice: 1500,
      },
      {
        articleId: 'art-002',
        name: 'Costume 2 Pièces',
        category: 'ceremonie',
        quantity: 1,
        unitPrice: 5000,
      }
    ],
    subtotal: 9500,
    discount: 500,
    discountType: 'amount',
    tax: 0,
    total: 9000,
    status: 'active',
    paid: true,
    withdrawn: false,
    paymentMethod: 'cash',
    depositDate: new Date(Date.now() - 24 * 3600 * 1000).toISOString().split('T')[0],
    paymentDate: new Date(Date.now() - 24 * 3600 * 1000).toISOString().split('T')[0],
    estimatedReadyDate: new Date(Date.now() + 24 * 3600 * 1000).toISOString().split('T')[0],
    createdBy: 'usr-cashier-1',
    createdByName: 'Mabiala Grâce (Caissier)',
    urgency: 'normal',
    notes: 'Priorité repassage col chemises',
    tags: ['Particulier', 'Habitué'],
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'ord-002',
    number: 'D-0043',
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    clientName: 'Sassou Yvonne',
    clientPhone: '+242055443322',
    clientEmail: 'yvonne.s@hotmail.com',
    clientAddress: 'Bacongo, Case de Passage',
    items: [
      {
        articleId: 'art-003',
        name: 'Robe de Soirée / Cérémonie',
        category: 'ceremonie',
        quantity: 1,
        unitPrice: 7000,
      }
    ],
    subtotal: 7000,
    discount: 0,
    discountType: null,
    tax: 0,
    total: 7000,
    status: 'active',
    paid: false,
    withdrawn: false,
    paymentMethod: null,
    depositDate: new Date().toISOString().split('T')[0],
    estimatedReadyDate: new Date(Date.now() + 48 * 3600 * 1000).toISOString().split('T')[0],
    createdBy: 'usr-client-web',
    createdByName: 'Demande En Ligne',
    urgency: 'express',
    notes: 'Livraison à domicile demandée',
    tags: ['En Ligne', 'Livraison'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'cli-001',
    name: 'Matingou Christian',
    phone: '+242066112233',
    email: 'christian.matingou@gmail.com',
    address: 'Poto-Poto, Rue Congo',
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    totalInvoices: 8,
    totalSpent: 72000,
    lastVisit: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    notes: 'Client VIP - Préfère les cintres en bois',
    createdAt: new Date(Date.now() - 90 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cli-002',
    name: 'Sassou Yvonne',
    phone: '+242055443322',
    email: 'yvonne.s@hotmail.com',
    address: 'Bacongo, Case de Passage',
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    totalInvoices: 3,
    totalSpent: 21000,
    lastVisit: new Date().toISOString(),
    notes: 'Demande systématique de livraison',
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const MOCK_STAFF: User[] = [
  {
    id: 'usr-owner-1',
    email: 'bello.owner@lbpressing.cg',
    role: 'owner',
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    fullName: 'Barry Bello (Propriétaire)',
    phone: '+242069000001',
    permissions: [
      { action: 'create_invoice', granted: true },
      { action: 'cancel_invoice', granted: true },
      { action: 'view_revenue', granted: true },
      { action: 'manage_users', granted: true },
      { action: 'modify_prices', granted: true },
      { action: 'export_data', granted: true },
    ],
    createdAt: new Date().toISOString(),
    isActive: true,
  },
  {
    id: 'usr-cashier-1',
    email: 'mabiala.grace@lbpressing.cg',
    role: 'caissier',
    pressingId: 'lb-pressing-org-001',
    organizationId: 'lb-pressing-org-001',
    fullName: 'Mabiala Grâce (Caissier)',
    phone: '+242069000002',
    permissions: [
      { action: 'create_invoice', granted: true },
      { action: 'cancel_invoice', granted: false },
      { action: 'view_revenue', granted: false },
      { action: 'manage_users', granted: false },
    ],
    createdAt: new Date().toISOString(),
    isActive: true,
  }
];
